### ISSUE TITLE
Error updating ImageCache(imagecache1) status to 'Aborted'

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#55]
I0501 12:23:22.302552       1 controller.go:125] Setting up event handlers
I0501 12:23:22.305612       1 fledged.go:74] Starting pre-flight checks
I0501 12:23:22.325033       1 controller.go:161] No dangling or stuck jobs found...
E0501 12:23:22.337601       1 controller.go:201] Error updating ImageCache(imagecache1) status to 'Aborted': ImageCache.fledged.k8s.io "imagecache1" is invalid: status.startTime: Invalid value: "null": status.startTime in body must be of type string: "null"
F0501 12:23:22.338115       1 fledged.go:76] Error running pre-flight checks: ImageCache.fledged.k8s.io "imagecache1" is invalid: status.startTime: Invalid value: "null": status.startTime in body must be of type string: "null"
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc000287500, 0xc00026a000, 0xe3, 0x135)
        /home/bhuvaneswari_senthilraja/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x1f21280, 0xc000000003, 0xc00009c230, 0x1e8e496, 0xa, 0x4c, 0x0)
        /home/bhuvaneswari_senthilraja/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x372
github.com/golang/glog.(*loggingT).printf(0x1f21280, 0x3, 0x140c225, 0x23, 0xc0000b1f00, 0x1, 0x1)
        /home/bhuvaneswari_senthilraja/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:655 +0x14b
github.com/golang/glog.Fatalf(...)
        /home/bhuvaneswari_senthilraja/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1148
main.main()
        /home/bhuvaneswari_senthilraja/src/github.com/senthilrch/kube-fledged/cmd/fledged.go:76 +0x616

**Comment by senthilrch** [comment]
PR #57
